module.exports = {
  apps: [
    {
      name: 'marcobot',
      script: 'src/bot.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: 'logs/error.log',
      out_file: 'logs/out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'mediaops',
      // Python venv interpreter — runs mediaops.server in SSE mode on port 8765.
      // cwd is the repo root so .env and relative paths (arrstack credentials)
      // resolve the same way as when claude spawns it as stdio.
      script: 'mcp/.venv/bin/python',
      args: ['-m', 'mediaops.server', '--transport', 'sse', '--port', '8765'],
      cwd: __dirname,
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        FASTMCP_HOST: '127.0.0.1',
        FASTMCP_PORT: '8765',
        PYTHONPATH: `${__dirname}/mcp/src`,
      },
      error_file: 'logs/mediaops-error.log',
      out_file: 'logs/mediaops-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'mediaops-restricted',
      script: 'mcp/.venv/bin/python',
      args: ['-m', 'mediaops.server', '--transport', 'sse', '--port', '8766'],
      cwd: __dirname,
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        FASTMCP_HOST: '127.0.0.1',
        FASTMCP_PORT: '8766',
        MEDIAOPS_PROFILE: 'restricted',
        PYTHONPATH: `${__dirname}/mcp/src`,
      },
      error_file: 'logs/mediaops-restricted-error.log',
      out_file: 'logs/mediaops-restricted-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
